server:
  log_level: info
  http_listen_port: 12345

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

integrations:
  agent:
    enabled: true

  loki:
    configs:
      - name: go-app-logs
        positions:
          filename: /tmp/pos.yaml
        scrape_configs:
          - job_name: go_app
            static_configs:
              - targets:
                  - localhost
                labels:
                  job: go_app
                  __path__: /var/log/myapp/server.log
