auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    shared_store: filesystem

limits_config:
  retention_period: 6h                  # Reduce in-memory buildup
  max_streams_per_user: 5000           # Prevent stream explosion
  max_entries_limit_per_query: 5000    # Cap query return size
  ingestion_rate_mb: 4                 # Limit ingestion bandwidth
  ingestion_burst_size_mb: 8           # Allow brief spikes
  max_query_parallelism: 2             # Avoid overwhelming on queries

chunk_store_config:
  max_look_back_period: 2h             # Don’t query too far back by default

table_manager:
  retention_deletes_enabled: true
  retention_period: 6h

ingester:
  max_chunk_age: 1m                    # Aggressively flush old chunks
  chunk_idle_period: 30s               # Flush idle streams faster
  chunk_retain_period: 1m              # Keep flushed chunks briefly
